DEVICE: cpu                             # device used for training

MODEL:
  NAME: rest                                          # name of the model you are using
  VARIANT: B                                          # sub name of the model you are using 
  PRETRAINED: 'checkpoints/rest/rest_base.pth'       # pretrained model path

TEST:
  FILE: 'assests/dog.jpg'               # filename or foldername (image mode)
  IMAGE_SIZE: [224, 224]                # inference image size